export * from './background-qc';
export * from './background-rtg';
export * from './truck-left';
export * from './truck-left-unladen';
export * from './truck-left-andon';
export * from './truck-right';
export * from './truck-right-unladen';
export * from './truck-right-andon';
export * from './vessel-shape-background';
